### ISSUE TITLE
Captcha required when social login with Google

### ISSUE THREAD

**Issue by kidandcat** [SAP/gigya-flutter-plugin#11]
Hello, when logging in with google, it throws an error:

`ERROR 401020: Login Failed Captcha Required {callId: 264bd1b9ba6a4b67805dd59d5931cb2a, errorCode: 401020, errorDetails: Login Failed Captcha Required, errorMessage: Login Failed Captcha Required, apiVersion: 2, statusCode: 401, statusReason: Unauthorized, time: 2021-06-10T10:05:28.931Z, errorFlags: captchaNeeded}`

How should we implement that captcha?

**Comment by tal-mi** [comment]
Captcha is currently not supported via the mobile SDKs/Flutter plugin.
It is an upcoming update.
I assume you received this error because Captcha is enabled on your site.
