### ISSUE TITLE
Hide screenset programatically

### ISSUE THREAD

**Issue by Dooks123** [SAP/gigya-flutter-plugin#15]
When using this to show a screenset:

    GigyaSdk.instance.showScreenSet(screenSet, (event, map) {
      debugPrint('Screen set event received: $event');
      debugPrint('Screen set event data received: $map');
      if (event == 'onHide' || event == 'onLogin') {
        setState(() {});
      }
    });

How can I close the screenset shown if there is an error event coming through?

**Comment by tal-mi** [comment]
Hi,
This feature is currently not available on our Core SDKs.
We will add it to our backlog in order to provide a viable solution.

Tal

**Comment by tal-mi** [comment]
Will be added to the upcoming release.

**Comment by tal-mi** [comment]
Feature introduced in v1.0.2
