### ISSUE TITLE
iOS showScreenSet "startScreen" parameter not taken into account

### ISSUE THREAD

**Issue by Dooks123** [SAP/gigya-flutter-plugin#16]
I have implemented the following code:

    GigyaSdk.instance.showScreenSet(screenSet, (event, map) async {
      if (event == 'onHide' || event == 'onLogin') {
        setState(() {});
      }
    }, parameters: {
      "startScreen": 'MobileLogin', <--- (Default is 'gigya-login-screen')
      "deviceType": 'mobile',
      "mobileScreenSet": screenSet,
    });

On Android it shows the correct startScreen, but on iOS it doesn't take the startScreen parameter into account.

**iOS Log:**
> Data - {data: {profile: {}, data: {}, preferences: {}, eventName: beforeScreenLoad, sourceContainerID: pluginContainer, source: showScreenSet, response: {}, instanceID: pluginContainer, subscriptions: {}, nextScreen: gigya-login-screen}, event: onBeforeScreenLoad}

As you can see the `nextScreen: gigya-login-screen` is wrong, doesn't show the correct screen there.

**Android Log:**
> Data - {data: {profile: {}, data: {}, preferences: {}, eventName: beforeScreenLoad, sourceContainerID: pluginContainer, source: showScreenSet, response: {}, instanceID: pluginContainer, subscriptions: {}, nextScreen: MobileLogin}, event: onBeforeScreenLoad}

This is the correct screen `nextScreen: MobileLogin`.

**Comment by Dooks123** [comment]
https://github.com/SAP/gigya-swift-sdk/issues/34#issue-988991770

**Comment by sagishm** [comment]
will fix it in the next release.

**Comment by tal-mi** [comment]
Fix available in v0.1.2
