### ISSUE TITLE
Error when linking accounts

### ISSUE THREAD

**Issue by kidandcat** [SAP/gigya-flutter-plugin#20]
I'm getting the following error when following these steps:

- Create a new account using Apple Social Login
- Logout
- Try to logging using Google Social Login with the same email
- A conflicting account is triggered, so I link the account to the existing apple with:
      `var res = await resolver.linkToSocial(SocialProvider.apple);`
- It fails with the next error:
```
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("callId"), #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      new GigyaResponse.fromJson (package:gigya_flutter_plugin/models/gigya_models.dart:35:22)
#2      new Account.fromJson (package:gigya_flutter_plugin/models/gigya_models.dart:82:42)
#3      _showLinkToSiteBottomSheet.<anonymous closure> (package:reactions/components/SocialButtons.dart:344:61)
<asynchronous suspension>
```

These steps works corretly for other linkings, for example Facebook -> Google, Google -> Facebook, etc

The executing code is (inside a try catch):
```
var res = await resolver.linkToSocial(SocialProvider.apple);
final Account account = Account.fromJson(res);
```

It looks like linkToSocial don't throw any error, but it returns null. The apple webview never opens.

**Comment by sagishm** [comment]
fixed in 0.1.3 release.
