### ISSUE TITLE
Google Social Login generic error

### ISSUE THREAD

**Issue by kidandcat** [SAP/gigya-flutter-plugin#22]
We are getting a generic 400 gigya error when using Google Login. It happens in random time intervals.

We are not able to reproduce locally, only when uploaded to the Play Store.

**Comment by tal-mi** [comment]
Are you able to provide us with some error logs so we can investigate this?
If not, please open a [support ticket ](https://developers.gigya.com/display/GD/Opening+A+Support+Incident) providing the necessary data (which cannot be shared in open source).

Regards,
Tal

**Comment by kidandcat** [comment]
Sorry for the late. I can't provide you with a reproducible error because it only happens in the production release of our app, and we are not able to reliable reproduce the issue in debug mode. Also it happens in random time windows.

**Comment by tal-mi** [comment]
I will investigate and update. Thank you for the info.

**Comment by ShestakovaOlga** [comment]
Hi,
we have new info from the error: `"Missing server client id. Check manifest implementation"`

**Comment by tal-mi** [comment]
Hi,

Please follow guidelines to make sure that the Google auth library is properly implemented.
https://sap.github.io/gigya-android-sdk/sdk-core/#google

**Comment by ShestakovaOlga** [comment]
Thanks for the quick response,
Yes, we followed that guide. And the "missing server client id..." was our fault, we ported the project to sound safety and we didn't configure it properly.

Now we configured it, and we got the same error as before. It seems to have more android stack traces now (or they may not be related, not sure):

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/39344982/164721737-44a2c5b7-7a40-4676-8f27-8867b4312eaf.png">

The last line full of nulls is us trying to print any info from the GigyaResponse:
`'Unknown Error ${e.errorCode} ${e.errorDetails} ${e.statusCode} ${e.statusReason} ${e.callId} ${e.mapped} ${e.toString()}'`

**Comment by tal-mi** [comment]
Your Android Core SDK is not yet configured correctly.
https://sap.github.io/gigya-android-sdk/sdk-core/#configuration

Please Add the HostActivity to your AndroidManifest.xml.

**Comment by ShestakovaOlga** [comment]
Hi,
thank you for your answers! We are still working on it. 
The link to the configuration page in the Google section in Readme points to https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD?locale=en-US .
I think it should point to https://sap.github.io/gigya-android-sdk/sdk-core/#configuration.

**Comment by tal-mi** [comment]
Thanks. I'll make the necessary updates.

**Comment by OSInteracso** [comment]
Hi,
now we have new error information: 
`Unknown Error 400 null 0 null  {localizedMessage: DEVELOPER_ERROR, callId: , errorCode: 400, statusCode: 0} Instance of 'GigyaResponse'`

**Comment by tal-mi** [comment]
Hi,

DEVELOPER_ERROR is returned from Google.
This means that your implementation is not correct via the Google API console.

**Comment by OSInteracso** [comment]
Hi,
we have fixed the error. In the end, we needed to add this line: `classpath 'com.google.gms:google-services:4.3.10'` to this file: `android/build.gradle`. Thanks for the help
