### ISSUE TITLE
Logout callback

### ISSUE THREAD

**Issue by vinzaceto** [SAP/gigya-flutter-plugin#23]
Looking at this link [https://help.sap.com/viewer/8b8d6fffe113457094a17701f63e3d6a/GIGYA/en-US/4137589670b21014bbc5a10ce4041860.html](url), in JS sdk there are some parameters to add on Logout, in particular a we can add a callback to check the response. How can I check error case? 
How can we do this on flutter?

**Comment by tal-mi** [comment]
Hi,

This feature is not supported by the Core native SDKs and therefore cannot be applied in the Flutter plugin.
It is currently not in our backlog.
You can register a feature request with [support](https://developers.gigya.com/display/GD/Opening+A+Support+Incident) for this.

Regards,
Tal
