### ISSUE TITLE
Forgot Password error

### ISSUE THREAD

**Issue by AiaRup** [SAP/gigya-flutter-plugin#24]
Hi!
We are using this plugin in our app and so far implemented login, register and social register, but we encountered a problem with the forgot password function. The problem occurs on IOS and Android.

We are using:
**gigya-flutter-plugin** - 0.1.1
**Swift SDK** (on IOS)

We get to the point where the source code enters the `forgot password` function and we can see that it receives successfully the email (loginId) :
 
![Screenshot 2021-11-02 at 12 05 37](https://user-images.githubusercontent.com/35365209/139827631-ba9699d1-55ff-45f7-822b-8d6cf8616875.png)

But it won't return the result, it just exits the app with the following error:

![Screenshot 2021-11-02 at 12 06 01](https://user-images.githubusercontent.com/35365209/139827777-cdd80e06-ad1e-43a7-ba17-dce3b93fc0b1.png)

Sometimes inside the parenthesis, there is a `long id` or a `200` status code, but it never reaches the line of returning the result (and therefore never enters our `then` or `catch` block).

To clarify, we DO get the email for resetting the password and this part works well!

![Screenshot 2021-11-02 at 12 21 02](https://user-images.githubusercontent.com/35365209/139829205-9c4915b5-7766-4907-b9b8-98f8b1b49151.png)

Our implementation of the forgot password function is taken from your [example code ](https://github.com/SAP/gigya-flutter-plugin/blob/main/example/lib/routes/forgot_password.dart)

```
 void sendRequest(
    String email,
  ) async {
      if (!_formKey.currentState.validate()) {
      return;
    }
    setState(() {
      _inProgress = true;
    });
      GigyaSdk.instance.forgotPassword(email).then((result) {
        setState(() {
        _inProgress = false;
        _requestResult = 'Forgot password success';
        showError = false;
        finished = true;
        });
        Get.back();
      }).catchError((err) {
        debugPrint('error $err');
        setState(() {
        _inProgress = false;
        _requestResult = '${err?.errorDetails}';
        showError = true;
        });
      });
  }
```

Thank you, we will much appreciate your help :)

**Comment by tal-mi** [comment]
Hi,

Please verify with the latest [release](https://github.com/SAP/gigya-flutter-plugin/releases/tag/v0.1.3) version.

Tal

**Comment by AiaRup** [comment]
Thank you so much Tal, it works great now!
Closing this issue.
