### ISSUE TITLE
Show Screenset fullscreen

### ISSUE THREAD

**Issue by vinzaceto** [SAP/gigya-flutter-plugin#25]
We are using the plugin to show screenset on our app. Using iOS We can see the webpage almost correct. Using Android, in the webview there is a white border and the page is not fullscreen. Looking at the Android Sdk, in the method showScreenset there is a parameter fullScreen to use but in your sdk this parameter  is not present.  Could be this parameter the problem? Can you help me? Please
![flutter_gigya_android](https://user-images.githubusercontent.com/35693341/139837745-607135a5-5b01-4742-8014-3781e37a79d3.png)

**Comment by tal-mi** [comment]
Hi,

I will investigate and resolve that for you.
Will update as soon as I find the cause.

Tal

**Comment by tal-mi** [comment]
Hi,

The plugin is designed to show the screensets in fullscreen mode only.
This is to avoid issues with the Android WebView height calculations.

You might need to check your screenset design to see why there are color changes.

Another option is to override the "gigya_fragment_webview.xml" file that is responsible for the screenset layout.
If you add your own file with the same name to your android res folder, it will override the core layout and you will be able to customize it. Just make sure that you do not change the ids of the elements.

Tal
