### ISSUE TITLE
Kakao Support

### ISSUE THREAD

**Issue by KarlChow92** [SAP/gigya-flutter-plugin#28]
Hello, I am wondering whether you will implement Login with Kakao support anytime soon. Are there any plans in the pipeline for this? 

Thanks!

**Comment by tal-mi** [comment]
Hi,
I will evaluate this and get back to you as soon as I can.

**Comment by KarlChow92** [comment]
Thank you so much!

**Comment by KarlChow92** [comment]
Hey @tal-mi did you had any chance to investigate? I checked out the repo and added `kakao` to `SocialProvider`. Then I tried to login through the pop up with that social provider but as soon as the pop up comes it shows: `Failed connecting. Pleasetry again later`. 
![IMG_E4F2E6B0F0A1-1](https://user-images.githubusercontent.com/2989224/174510607-98f53b6c-cf97-4a3d-910a-bcc104f30067.jpeg)

**Comment by tal-mi** [comment]
You are missing the redirect url setting in your site.
Add "gigya://gsapi/YOUR-APP-ID/login_result to the trusted URL section of your site settings.

I will add the Kakao provider to the SDK in the upcoming release.
