### ISSUE TITLE
Getting error message on register users

### ISSUE THREAD

**Issue by AiaRup** [SAP/gigya-flutter-plugin#3]
Hi there!
We are using your awesome plugin in our app, and we encountered a problem with getting the exact error message.

We are using: 

- gigya-flutter-plugin - 0.0.2
- Swift SDK (on IOS)

For example, on login error, we get the exact error message in the `errorDetails` property: 

<img width="644" alt="Screenshot 2021-02-22 at 17 23 21" src="https://user-images.githubusercontent.com/35365209/108730267-08200f00-7534-11eb-8030-125785742e3e.png">

But, if we get an error on register a new user, we get a **Validation failed** on the `errorDetails` property:

![Screenshot 2021-02-22 at 16 22 08](https://user-images.githubusercontent.com/35365209/108729654-6e586200-7533-11eb-8e10-f666c3ce2d38.png)

We looked a bit in the source code of the plugin and we found that the error message is on a property called `ValidationErrors`: 

![Screenshot 2021-02-19 at 12 39 25](https://user-images.githubusercontent.com/35365209/108729396-25081280-7533-11eb-8f5a-79c9de14ddb0.png)

But this property is not included in the gigya_models.dart file:

![Screenshot 2021-02-19 at 12 48 39](https://user-images.githubusercontent.com/35365209/108729524-49fc8580-7533-11eb-994b-c708f26b593a.png)

We are not sure if it is intended to be this way, or if it is possible to retrieve the error in another way?

We tried to add to the models file an attribute like `validationErrors = json['validationErrors']?.elementAt(0)['message']`, and it works on registration error, but gives some trouble on succesful login.

Just for some context, we used your code in the example folder on this repo:
```
void onLoginPress(user, password) async {
    setState(() {
      _inProgress = true;
    });
    GigyaSdk.instance.login(user, password).then((result) {
      final response = Account.fromJson(result);
      setState(() {
        _inProgress = false;
        _requestResult = 'Login success:\n\n ${response.uid}';
      });
      Get.offAll(GigyaLoginChecker());
    }).catchError((error) {
      setState(() {
        _inProgress = false;
        _requestResult = 'Register error\n\n${error.errorDetails}';
      });
    });
  }

```
We will much appreciate your help :)

**Comment by tal-mi** [comment]
Hi there,

Thanks for reporting this issue.
We will be looking into a permanent solution to tackle this problem.

In the meantime, we suggest you add a dynamic value to the GigyaResponse object that will take the entire json when generated.

Object should look as follows:

class GigyaResponse {
  String callId;
  int statusCode = 200;
  int errorCode = 0;
  String errorDetails;
  String statusReason;
  int apiVersion;
  String regToken;
  **dynamic mapped;**

  Interruption getInterruption() {
    switch (errorCode) {
      case 403043:
        return Interruption.conflictingAccounts;
      case 206001:
        return Interruption.pendingRegistration;
      case 206002:
        return Interruption.pendingVerification;
      default:
        return null;
    }
  }

  GigyaResponse.fromJson(dynamic json)
      : callId = json['callId'],
        statusCode = json['statusCode'],
        errorCode = json['errorCode'],
        errorDetails = json['errorDetails'],
        statusReason = json['statusReason'],
        apiVersion = json['apiVersion'],
        regToken = json['regToken'],
        **mapped = json;**

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['callID'] = callId;
    data['statusCode'] = statusCode;
    data['errorCode'] = errorCode;
    data['errorDetails'] = errorDetails;
    data['statusReason'] = statusReason;
    data['apiVersion'] = apiVersion;
    data['regToken'] = regToken;
    data['mapped'] = mapped;
    return data;
  }
}

Regards,
Tal

**Comment by AiaRup** [comment]
Hi @tal-mi ,

Thank you so much for the fast answer!
The ** mapped** solution works great for now. 
We will follow the issue to see if you have new updates.

Thanks again!

**Comment by tal-mi** [comment]
Hi,

Sure, I will continue to update the issue until we provide a clear update for this.

Regards,
Tal

**Comment by tal-mi** [comment]
Hi,

The suggested solution has been updated in version 0.0.3.

Thanks,
Tal
