### ISSUE TITLE
Sign in with Apple is throwing an error

### ISSUE THREAD

**Issue by smouelhi** [SAP/gigya-flutter-plugin#32]
Configuration on CDC done.

Using the example app provided with the flutter SDK, the apple login is not working.

A popup screen appears and mentions "failed connecting. Please try again later."

Here is the code relevant to the GigyaSDK setup: 

```
case SocialAuthenticationType.apple:
  {
    GigyaSdk.instance
        .socialLogin(SocialProvider.apple)
        .then((result) {
      print(result);
    });
  }
```

Your help would be much appreciated.
![Screenshot 2022-11-11 at 10 11 09 PM](https://user-images.githubusercontent.com/4283984/201402574-eff22948-7a0d-4885-be43-fd6409519b7f.png)

**Comment by smouelhi** [comment]
Do we need to add the capability Sign in with Apple in the Runner's capabilities list?

**Comment by karim-8** [comment]
The same case Happening to me Is there anyone found a solution yet?

**Comment by sagishm** [comment]
Hi,
it's looks like something incorrect in your implementation, make sure you add the `AppleSigninWrapper.swift` to your `Runner`, also check if you set correctly everything in our docs.
Please follow our Apple Sign in documentation: 
https://sap.github.io/gigya-swift-sdk/GigyaSwift/#apple
https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/4143475570b21014bbc5a10ce4041860.html?q=apple%20sign%20in

Thanks

**Comment by karim-8** [comment]
I'm just trying to run the example provided, but this screen happened to me also Do I need to check any Implementation inside the example?
https://user-images.githubusercontent.com/4283984/201402574-eff22948-7a0d-4885-be43-fd6409519b7f.png

**Comment by sagishm** [comment]
Apple sign in is cupeled to BundleID, you need to configurate everything to your BundleID.

**Comment by smouelhi** [comment]
Hi Sagish,

We followed the same documentation, but can't find AppleSigninWrapper.swift. It is mentioned "import" but I guess it should be either brought from your example project, or it has to be implemented by us? It's unclear to me.

**Comment by smouelhi** [comment]
Maybe it's worth I describe the whole setup we have done.

1. We have configured Apple Sign In from CDC, as per this [documentation](https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/4143475570b21014bbc5a10ce4041860.html?q=apple%20sign%20in)
2. We have added the Sign in Capability from our Xcode project
3. The missing step could be AppleSigninWrapper.swift, but as per your documentation, it is mentioned 
``` 
After you have added AuthenticationServices.framework to your project you next need to import the AppleSigninWrapper.swift file from the GigyaProviders dictionary to your Xcode project.
```

It is unclear to me if we need to write the AppleSigninWrapper.swift in our runner, the same way as GoogleWrapper, or it is provided somewhere and we need to put it in the GigyaProviders. 

From your example project, only Google and Facebook examples are provided.

Thanks.

**Comment by smouelhi** [comment]
Hi Sagish,

We finally found the files in the provider folder that is hosted in the GitHub project of Gigya Swift SDK. https://github.com/SAP/gigya-swift-sdk/releases/tag/1.4.0 

I suggest adding this link or reference in the documentation, as it was not clear at all where to get it from. 

If your documentation is open source, I'm happy to provide a PR for it.

**Comment by sagishm** [comment]
The project is open source but documentation still needs verification from our documentation team, i will forward you suggestion to them.
Thanks

**Comment by QRCharlie** [comment]
For future reference, you need to add **registerSocialProvider** to the **AppDelegate.swift**.
Unfortunately it is not mentioned in the current documentation, nor the example provided uses Apple Sign In.

Here's what you need to add
`Gigya.sharedInstance(GigyaAccount.self).registerSocialProvider(of: .apple, wrapper: AppleSignInWrapper())`

Complete code for AppDelegate, including provider wrappers for Google and Facebook, as follows

```
override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    SwiftGigyaFlutterPlugin.register(accountSchema: GigyaAccount.self)
    
    // Gigya Auth providers
    Gigya.sharedInstance(GigyaAccount.self).registerSocialProvider(of: .google, wrapper: GoogleWrapper())
    Gigya.sharedInstance(GigyaAccount.self).registerSocialProvider(of: .facebook, wrapper: FacebookWrapper())
    Gigya.sharedInstance(GigyaAccount.self).registerSocialProvider(of: .apple, wrapper: AppleSignInWrapper())
    
    // Facebook SDK init
    ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

```
