### ISSUE TITLE
Gradle plugin support for Kotlin Gradle plugin version 1.5.20 and higher

### ISSUE THREAD

**Issue by smouelhi** [SAP/gigya-flutter-plugin#36]
When using Gradle 7 for the build, and error is thrown:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':gigya_flutter_plugin' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

A kotlin garde plugin upgrade would be required for the next releases.

**Comment by navaronbracke** [comment]
This should be fixed by https://github.com/SAP/gigya-flutter-plugin/commit/6c52065e6223816189d6b7b257d88b6919457774 which bumps the version to `1.6.10`.

We could bump it even further to 1.7, but this should at least unblock using Gradle 7.
