### ISSUE TITLE
SessionInfo.expirationTime access on android crashing, since parsing logic is not handled for android

### ISSUE THREAD

**Issue by jabershabeek** [SAP/gigya-flutter-plugin#39]
SessionInfo.expirationTime access on android crashing, since parsing logic is not handled for android

Removing the Platform.isIOS check will solve the issue

**Comment by sagishm** [comment]
as in open source project you are welcome to open PR :) .

**Comment by jabershabeek** [comment]
@tal-mi please help check this PR.
