### ISSUE TITLE
GigyaError with all null values - 1.0.0

### ISSUE THREAD

**Issue by mcg95** [SAP/gigya-flutter-plugin#48]
Hi. I am using the latest version(1.0.0) of this plugin and when I use GetIt.I<GigyaSdk>().send() function, whenever an error occurs, the GigyaError object seems to be having all null values when debugging from Flutter side. But when debugging the native code, I can see that the error is returned with data. There seems to be some data loss when sending the data from iOS/Android to Flutter.

gigya_flutter_plugin - 1.0.0
iPhone SE 3rd Gen Simulator - iOS 16.2
Pixel 4 (API 29)

**Comment by navaronbracke** [comment]
I can reproduce this when running the example app.

For example if I do `loginWithCredentials` and pass in some bad email address I get ```
LoginApiError<GigyaAccount>(error: Gigya.NetworkError.gigyaError(data: Gigya.GigyaResponseModel(statusCode: Gigya.ApiStatusCode.unknown, errorCode: 403042, callId: "3811fa913ef3466ea8a06f839e1f1de3", errorMessage: Optional("Invalid LoginID"), sessionInfo: nil, requestData: Optional(277 bytes))), interruption: nil)
``` In XCode, but on the Dart side, I get all null values as reported.

**Comment by navaronbracke** [comment]
I have a fix in the works, I'll get this out later today for review.

**Comment by tal-mi** [comment]
v1.0.0 availalbe.
