### ISSUE TITLE
Login session is lost after reopen the app

### ISSUE THREAD

**Issue by githubsureshmusham** [SAP/gigya-flutter-plugin#60]
Hi @tal-mi 
I noticed that after I log in with an active user in the gigya-flutter-plugin app, the active login session is not retained if I close the app and reopen it again. 
Could you please help me if there is any parameter set to retain the login session even after I close the app and reopen.

Regards
Suresh

**Comment by dhoskins** [comment]
Noticed the same. Wondering if this will be fixed in recently released v1.0.0.

**Comment by dhoskins** [comment]
This error still seems to be present in v1.0.0. Surely this is a fundamental high-priority issue for this SDK?

**Comment by tal-mi** [comment]
1.0.1 is expected tomorrow with a fix for this issue.

**Comment by tal-mi** [comment]
v1.0.1 available

**Comment by githubsureshmusham** [comment]
> v1.0.1 available

Thank you, now the user session is persisted even after I restart the app. 
Thank you very much for the fix.
