### ISSUE TITLE
Gigya signup using credential getting Null error code.

### ISSUE THREAD

**Issue by ke-utkarsh** [SAP/gigya-flutter-plugin#62]
I am trying to implement Gigya signup using credentials and forgetPassword in Flutter. I are getting this  400106 Not connected User is not connected to the required network or to any network. error code and description when I am trying to call gigya.register(..) via gigya_flutter_plugin ^0.1.6 version. How to resolve this error.

Also I am not able to initialize gigya using 1.0.0 version. I have followed step by step guide given on [https://github.com/SAP/gigya-flutter-plugin](https://stackoverflow.com/). Any implemented working code in flutter using 1.0.0 will also be helpful.

Also using example app provided on flutter plugin repo is also giving null error on Signup using credential. Sending this parameter.

Map<String,dynamic>();
profile["${FIRST_NAME_KEY}"] = 'Harsh';
profile["${COUNTRY_KEY}"] = COUNTRY_VALUE;

final temp = Map<String,dynamic>();
temp["${NUMBER_KEY}"] = '9********0';

profile["${PHONE_KEY}"] = temp;

param["${PROFILE_KEY}"] = profile;

final finalparam = HashMap<String,dynamic>();
finalparam["${PROFILE_KEY}"] = profile;

response = await gigya.register(
'hars*******@gmail.com',
'Password@1234', params: finalparam);

**Comment by navaronbracke** [comment]
@ke-utkarsh Does this still reproduce with version 1.0.1 ?
