### ISSUE TITLE
Could not retrieve gigya-android-sdk:sdk-core:core-v6.2.1

### ISSUE THREAD

**Issue by michaelferwer** [SAP/gigya-flutter-plugin#63]
Hello,

On Android, when I want to run my application in debug mode, I have an error to retrieve sdk-core dependency for gigya-android-sdk.

> Could not find com.github.SAP.gigya-android-sdk:sdk-core:core-v6.2.1.

When I go to https://jitpack.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v6.2.1/sdk-core-core-v6.2.1.pom to see the dep. I have the following error : 

> Build failed. See the log at jitpack.io

On release mode, I have this issue :

> Failed to transform sdk-core-core-v6.2.1.aar (com.github.SAP.gigya-android-sdk:sdk-core:core-v6.2.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find sdk-core-core-v6.2.1.aar (com.github.SAP.gigya-android-sdk:sdk-core:core-v6.2.1).
        Searched in the following locations:
            https://jitpack.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v6.2.1/sdk-core-core-v6.2.1.aar

Thank you in advance for your support.

**Comment by michaelferwer** [comment]
It's appear the dependency is up again. 

That's very strange.

**Comment by tal-mi** [comment]
Github issue. Looking into it.

**Comment by michaelferwer** [comment]
Hello @tal-mi , 

Do you have any update on this issue ?

Now I have this following error when I want to release my application :

> Execution failed for task ':gigya_flutter_plugin:generateReleaseRFile'.
> Could not resolve all files for configuration ':gigya_flutter_plugin:releaseCompileClasspath'.
   > Could not find com.github.SAP.gigya-android-sdk:sdk-core:core-v6.2.1.
     Required by:
         project :gigya_flutter_plugin

**Comment by tal-mi** [comment]
Working on it. Its high priority.

**Comment by tal-mi** [comment]
Issue resolved. Sorry for the delay.
