### ISSUE TITLE
SDK swallows login exception details

### ISSUE THREAD

**Issue by dhoskins** [SAP/gigya-flutter-plugin#65]
When logging in with invalid username and password, the method `GigyaError.fromPlatformException` returns `const GigyaError()`. The interesting details of the exception are not passed through to the calling method.

**Comment by navaronbracke** [comment]
This is a duplicate of #48. This bug has been fixed by #61, but that fix has not yet been approved.

**Comment by dhoskins** [comment]
I've tried this fix, but still important information is not being surfaced. When attempting registration for example, the `details` map in the `PlatformException` passed to `GigyaError.fromPlatformException` can contain useful details such as `validationErrors`.

**Comment by navaronbracke** [comment]
So you don't see the `validationErrors` object inside the details, when trying to register? Or is the value incomplete?

**Comment by tal-mi** [comment]
v1.0.1 available.
