### ISSUE TITLE
Differing behaviour between platforms on account linking

### ISSUE THREAD

**Issue by Joanna-OI** [SAP/gigya-flutter-plugin#66]
When a user links a social media account to an existing account from the `showScreensets` view, the plugin behaves differently on Android and iOS.

On Android, after a successful linking, the user is automatically logged in and an `onLogin` event is emitted.

On iOS, after a successful linking, the user is not automatically logged in (can be verified with the `isLoggedIn` function), and the screen sets automatically close. The user then needs to login again.

The preferred behaviour would be for both Android and iOS to automatically log in the user after linking their accounts.

**Comment by sagishm** [comment]
Fixed in last release.
