### ISSUE TITLE
onLogin sessionInfo missing on iOS

### ISSUE THREAD

**Issue by QRCharlie** [SAP/gigya-flutter-plugin#70]
Hello,
using version 1.0.1 with screen-sets I correctly receive `sessionInfo` as the `event.data` of `onLogin` on Android, **but not on iOS**.
I just upgraded from 0.1.7 where it was working on both platforms.

`showScreenSet` parameters include 
`"include": "profile, data, id-token, preferences, subscriptions, groups"`

On iOS sessionInfo is missing.

Thanks

**Comment by sagishm** [comment]
Fixed in last release.
