### ISSUE TITLE
`cname` argument missing in sdk.init call

### ISSUE THREAD

**Issue by nemscep** [SAP/gigya-flutter-plugin#71]
Hello there! 
It seems that configuring the sdk with json or cname is not possible in 1.0.1 🤔 
Would it be possible to add `cname` argument in sdk init method, since android and ios support it and currently just don't use it, or generally to support initialization of the sdk using a json file 🤷‍♂️ 

Thanks! :v:

**Comment by navaronbracke** [comment]
I had a quick look at the docs. It should be simple enough to just plumb through the `cname` to `initFor()` (Swift) and `init()` (Android)

Since both methods only have three arguments (cname being the last one in either case), I don't see the benefit of having initialization through a JSON file.

**Comment by nemscep** [comment]
> I had a quick look at the docs. It should be simple enough to just plumb through the `cname` to `initFor()` (Swift) and `init()` (Android)
> 
> Since both methods only have three arguments (cname being the last one in either case), I don't see the benefit of having initialization through a JSON file.

Already done it, PR will be ready soon 😉

**Comment by navaronbracke** [comment]
@nemscep It looks like the web sdk does not support it, so I'll update my Web SDK platform interface implementation to just ignore the parameter.

**Comment by nemscep** [comment]
Here it is! https://github.com/SAP/gigya-flutter-plugin/pull/72
Thanks for the support @navaronbracke 🤟
