### ISSUE TITLE
I am getting write mode violation error on sending phone number while doing registration in gigya through flutter. 

### ISSUE THREAD

**Issue by swastiiijain** [SAP/gigya-flutter-plugin#73]
Error retrieving thread information: (ipc/mig) server died
flutter: Error : GigyaError(apiVersion: 2, callId: 6d30d272caa042ce98faf3ca19f15893, details: {statusCode: 400, time: 2023-08-11T07:43:13.138Z, statusReason: Bad Request, errorDetails: Validation failed, validationErrors: [{message: write access mode violation, fieldName: profile.phones.type, errorCode: 400025}, {message: write access mode violation, fieldName: profile.phones.default, errorCode: 400025}]}, errorCode: 400009, errorMessage: Validation error, )
flutter: stacktrace : #0      MethodChannelGigyaFlutterPlugin.register
gigya_flutter_plugin_method_channel.dart:246
<asynchronous suspension>
#1      _RegisterWithEmailPageState._register
register_with_email_page.dart:30
<asynchronous suspension>

**Comment by navaronbracke** [comment]
During registration, you cannot set the value for `profile.phones.type`, at least that's what I think the issue is.

See https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/416d41b170b21014bbc5a10ce4041860.html#error-code-definitions-table

**Comment by sagishm** [comment]
Write access is not available for `profile.phones.type`, server restriction by design.
