### ISSUE TITLE
[Android] `getAccount()` fails to parse PlatformException due to offline

### ISSUE THREAD

**Issue by escargot9101** [SAP/gigya-flutter-plugin#74]
(plugin version: 1.0.1)

When `getAccount()` is called offline, it catches `PlatformException`.

on Android: (`details` is Map)
```
PlatformException(400106, User is not connected to the required network or to any network, {localizedMessage: User is not connected to the required network or to any network, errorCode: 400106, statusCode: 0}, null)
``` 

on iOS: (`details` is null)
```
PlatformException(700, The operation couldn’t be completed. (Gigya.NetworkError error 2.), null, null)
```

---

On Android, the `PlatformException.details` doesn't have `apiVersion` key and `GigyaError.fromPlatformException` don't allow `apiVersion` to be null.
```
  factory GigyaError.fromPlatformException(PlatformException exception) {

    if (details is! Map<Object?, Object?>) {
      return const GigyaError();  // on iOS, return on this line
    }

    // Remove the specific error details, to avoid including them twice.
    final int apiVersion = details.remove('apiVersion') as int; // <- on Android, thrown Exception here*
    final String? callId = details.remove('callId') as String?;
    final int? errorCode = details.remove('errorCode') as int?;
    ...
```

*thrown exception message:
```
GigyaSdk.getAccount throws type 'Null' is not a subtype of type 'int' in type cast.
```

I guess this is unexpected behavior and would like to be fix it if possible.

Thank you.

**Comment by navaronbracke** [comment]
We get the error code and message as expected, but we shouldn't crash when trying to parse the details.

The `apiVersion` field _is_ an `int?` in the `GigyaError` class, so we should have casted it to `int?`.

I'll look into patching this.
