### ISSUE TITLE
Google Social Login missing error info

### ISSUE THREAD

**Issue by kidandcat** [SAP/gigya-flutter-plugin#9]
Hi, we have setup google social login. When we launch google's social login, the native google login screen is launched, but after selecting a google account and coming back to our application, we receive a 400 error with no errorReason, so we cannot find out what's failing.

We have followed all the instructions in Gigya's core SDK to enable Google sign-in.

# Code fragment:
```
try {
              var result =
                  await GigyaSdk.instance.socialLogin(SocialProvider.google);
              print('---------------  Social Login Google OK');
              print('---------------  $result');
            } on GigyaResponse catch (e) {
              print('---------------  Social Login Google ERROR');
              print('STATUS ${e.statusCode}: ${e.statusReason}');
              print(
                  'ERROR ${e.errorCode}: ${e.errorDetails} callId: ${e.callId}');
              print('INTERRUPTION ${e.getInterruption()}');
              print('------------------------------------------');
```

# Output

```
I/flutter ( 2970): ---------------  Social Login Google ERROR
I/flutter ( 2970): STATUS 0: null
I/flutter ( 2970): ERROR 400: null callId:
I/flutter ( 2970): INTERRUPTION null
I/flutter ( 2970): ------------------------------------------
```

# Versions: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [VersiÃ³n 10.0.19042.985], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[!] Android Studio (not installed)
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)
```

```
  gigya_flutter_plugin:
    dependency: "direct main"
    description:
      name: gigya_flutter_plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.6"
```

**Comment by tal-mi** [comment]
Can you please specify the steps you took to implement Google sign-in in your application?

Regards,

Tal

**Comment by kidandcat** [comment]
We followed these steps: https://sap.github.io/gigya-android-sdk/sdk-core/#google

Then in Google console we created a new project. In the Credentials section, we added a new OAuth credential for Android. And we put that client_id in the meta tag inside the AndroidManifest.xml

Then in Gigya, in the Providers Configuration section, enabled Google and put there the client_id.


Because there is this paragraph: "Note that the required client_id is the Web client id generated when you create your Google project. This should not be mistaken with the Android OAuth client id. Make sure that your Google project contains both."

We tried to create a OAuth Web credential, and use that instead of the Android one, but we get the same error 400.

**Comment by tal-mi** [comment]
Thank you for the info:

Here are a few pointers:
On your API console please make sure you update the following redirect URI (according to your data center).
https://user-images.githubusercontent.com/47209216/121140602-b3827480-c842-11eb-82a1-3fc57b4f0fa4.png

In addition, the sample application is already configured to use the Google sign in,
All you need to do is add the following package to your *pubspec.yaml*
```
google_sign_in: ^5.0.4
```

**Comment by kidandcat** [comment]
Still not getting it to work. So we must create and use a OAuth Web Credential instead an Android credential?

**Comment by kidandcat** [comment]
Finally got it working. Our main trouble was not clearly understanding that Note and, not thinking that hot restart of flutter app doesn't reload Android `strings.xml` or any other files.
